#!/usr/bin/env bash

function ssh_cmd() {
  local rc="
  [[ -r /etc/profile ]] && source /etc/profile
  if [[ -r ~/.bash_profile ]]; then
    source ~/.bash_profile
  elif [[ -r ~/.bash_login ]]; then
    source ~/.bash_login
  elif [[ -r ~/.profile ]]; then
    source ~/.profile
  fi
  export PATH=\$PATH:\$SSHHOME
  source \$SSHHOME/.sshrc"

  local bootstrap="
  # Copy .sshrc and .sshrc.d; clean up when leaving
  export SSHHOME=\$(mktemp -d -t .$(whoami).sshrc.XXXXXXXX)
  export SSHRCCLEANUP=\$SSHHOME
  trap \"rm -rf \$SSHRCCLEANUP; exit\" 0
  echo $'$(tar c -h -C "${SSHHOME}" ${files:=$1} | openssl enc -base64)' \
    | openssl enc -base64 -d \
    | tar mx -C \$SSHHOME

  # Copy sshrc binary, so we can run sshrc again from the new host
  echo $'$(cat "$0" | openssl enc -base64)' \
    | openssl enc -base64 -d > \$SSHHOME/sshrc
  chmod +x \$SSHHOME/sshrc

  # Copy bootstrap rcfile
  echo $'${rc}' > \$SSHHOME/sshrc.rc

  # Create a wrapper around bash and use that as the shell
  echo 'bash --rcfile \$SSHHOME/sshrc.rc \"\$@\"' > \$SSHHOME/sshrcsh
  chmod +x \$SSHHOME/sshrcsh
  SHELL=\$SSHHOME/sshrcsh
  [ -e /etc/motd ] && cat /etc/motd
  \$SSHHOME/sshrcsh"

  echo "
  # Bail if openssl isn't installed on the remote host
  if [ ! \$(command -v openssl) ]; then
    echo >&2 \"error: sshrc requires openssl to be installed on the server\"
    exit 1
  fi

  # Compress bootstrap script for faster ssh connection and reduced risk of
  # ssh command being rejected by the server
  eval \"\$(echo $'$(echo "${bootstrap}" | gzip -c | openssl enc -base64)' \
    | openssl enc -base64 -d \
    | gzip -d)\""
}

function main() {
  [[ $# -lt 1 ]] && return $(ssh)

  if [[ ! $(command -v openssl) ]]; then
    echo >&2 "error: sshrc requires openssl to be installed locally"
    exit 1
  fi

  if [[ -z "${SSHHOME}" ]]; then
    for SSHHOME in $PWD $HOME; do
      [[ -f "${SSHHOME}/.sshrc" ]] && break
    done
  fi

  local files
  if [[ -f "${SSHHOME}/.sshrc" ]]; then
    files="${files} .sshrc"
  else
    echo >&2 "error: could not find .sshrc in current directory or $HOME"
    exit 1
  fi
  [[ -d "${SSHHOME}/.sshrc.d" ]] && files="${files} .sshrc.d"

  local size=$(tar cz -h -C "${SSHHOME}" ${files} | wc -c)
  if [ "${size}" -gt 65536 ]; then
    echo >&2 "
    error: .sshrc.d and .sshrc files must be less than 64kb
    current size: ${size} bytes"
    exit 1
  fi

  ssh -t "$@" "$(ssh_cmd "${files}")"
}

main "$@"
